### ISSUE TITLE
Ghar - Rampup and Onboarding

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#1]
We will use this issue to track onboarding and rampup to Ghar Tech team.

Zoho link - https://creator.zoho.in/userhome/navgurukul/admindashboard#/

We will approach in 3 phases
Phase 1 : Understand Zoho
Phase 2: Understand SQL, Ghar vision and present learning to team
Phase 3 : Build Sample App

****Week 1** - Understand Zoho and Low code development**

- [x] What is Lo-code development (https://www.zoho.com/creator/low-code-manual.html?src=hdd)
- [x] https://www.zoho.com/creator/videos/getting-started-zoho-creator.html
- [x] https://www.zoho.com/creator/videos/create-forms.html
- [x] https://www.zoho.com/creator/videos/import-data.html
- [ ] https://www.zoho.com/creator/videos/relationships.html
- [ ] https://www.zoho.com/creator/videos/list-reports-and-navigation.html
- [ ] https://www.zoho.com/creator/videos/calendar-reports.html
- [ ] https://www.zoho.com/creator/videos/workflows-zoho-creator.html
- [ ] https://www.zoho.com/creator/videos/pages-zoho-creator.html
- [ ] https://www.zoho.com/creator/videos/buttons-zoho-creator.html
- [ ] https://www.zoho.com/creator/videos/deluge-zoho-creator.html
- [ ] Getting Started With Zoho Creator Part 1 - App and Form Creation - YouTube - https://www.youtube.com/watch?v=7BPdK9odMlE
- [ ] Getting Started With Zoho Creator Part 2 - Create Custom Pages - YouTube - https://www.youtube.com/watch?v=3vhLh_Bt3lw&t=563s

**Week 2 : DB fundamentals, Ghar visions and deep dive topics**

- [ ] Intro to SQL: Querying and managing data \| Khan Academy - https://www.khanacademy.org/computing/computer-programming/sql#sql-basics
- [ ] Ghar - Vision and Proposal - Google Docs. -https://docs.google.com/document/d/1pRseCYThtgSZXcrZB2KlSMaQAnRklMFkCPbBk1qdr9E/edit#
- [ ] Pick a topic to   present (to team) from list below and start prepping : https://docs.google.com/document/d/1uQ48B50O33XJqlo9GvNkF46QDDGc_sBlFd-srw8I6V0/edit#

**Week 3 /4 : Topics sharing and Sample Apps**

- [ ] Start developing Sample app (See Onoarding guide above for details)
- [ ] Do a presentation of one topic of choice (See Onoarding guide above for details)

**Comment by ujjwal15718** [comment]
learn about Zoho form, the formula used, import/export data need to learn more it's really interesting
