### ISSUE TITLE
Tagging the partnerships team for campus capacity update messages.

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#106]
Tag the partnerships team for campus capacity update messages. 
Along with Dashboard link https://ghar.zohocreatorportal.in/#Page:Campus_Vacancy_Dashboard

[@Nikesh Dhruw] (https://navgurukul.slack.com/team/U05HB1GBVME)
[@Hemant] (https://navgurukul.slack.com/team/U05LRTQUMFU)
[@Shreedhar] (https://navgurukul.slack.com/team/U05FX1MMAES)
[@Lakshmi (She/Her)] (https://navgurukul.slack.com/team/U04UG3FBBNX)

**Comment by VarshaRajput12** [comment]
Closed the issue by adding the "Partnership Team" members in to notification.

**Comment by Nikesh** [comment]
Hi @shashi-NG @VarshaRajput12 looks like you guys have added me here by mistake. Please remove me from this repo.
