### ISSUE TITLE
Weekly updates tracker

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#11]
### Area: [Area Name]
**Completed :** 

> - Update text here
> - Update text here

**Pending :** 

> - Update text here
> - Update text here

**Blockers :** 

> - Update text here
> - Update text here

**Comment by abhilashnavgurukul** [comment]
### Area: Admissions
**Completed :**
**Pending :**

- AD - 5 - Ability to manage different schools
- Learning feature PRD
- Offer Letter Template Feature 
- SMS feature
- Interview Scheduling
- Team Zoho Creator learning

**Blockers :**

- Waiting for Interview Scheduling design
- Offer letter template - waiting for strapi migration
- Unable to send SMS to unverified number
- Bugs and Regressions in AD-5 implementation.

**Comment by abhilashnavgurukul** [comment]
### _Area: AD -5 Ability to manage different schools_
**Completed :**

> - Add New Campuses, New schools to campuses, and add stages to schools
> - Backend Repo merge issues (around 100 commits behind) resolved
> - First round of testing complete


**Pending :**

> - Change schools, Add transitions for all the schools
> - Add a feedback mechanism for all the schools
> - Send offer letters to students of each school and campus.
> - E2E Testing
> - Work on Deadline and Finished columns


**Blockers :**

```
```

### Area: Offer Letter Template
**Completed :**

> - Research on identifying solutions.


 **Pending :**

> - Backend to use Strapi for template content management.
> - Frontend to use the updated Strapi backend API
> - E2E testing

**Blockers :**

`- Waiting for Meraki migration to Strapi backend. Meraki and Curriculum team are working on it. Estimated to be done by 23rd June 2023`

 
### Area: Ability to send email, sms, and WhatsApp notification on stage transitions
**Completed :**

> - Aws Sns setup
> - Aws email setup
> - Sending email in a sandbox environment
> - Sending SMS in a sandbox environment
> - We have scoped down to only support SMS for now
> - Move out of the sandbox environment.
> - Backend update to send any SMS to any user.


**Pending :**
> - Backend update to send SMS on test fail or pass.
> - Backend update to send SMS when offer letter is sent.
> - Frontend update to send SMS on stage transition.
> - E2E Testing

**Blockers :**

```
- Waiting for aws team to approve the request to move sns environment out of the sandbox.
- Email notification development stopped due to the time taken to implement the feature.
```

 
### Area: Interview Scheduling
**Completed :**

> - None

**Pending :**

> - Ux Design
> - Backend updates
> - Frontend updates
> - E2E Testing

**Blockers :**

`

> > - Ux Design not ready. Narendra to update the status today.

`

 
### Area:Ghar Onboarding
**Completed :**

> - 4 Developers all on Ghar onboarding tasks, going through onboarding material, willl develop sample apps in a couple of weeks
> - Requirements gathering - First Round of Academic Associates Interviews complete
> - Collate interview notes
> - PRD Draft - User Management

**Pending :**

> - Second round of interviews.
> - PRD Draft - Learning Track
> - PRD finalization - User Management.
> - PRD finalization - Learning Track.

**Blockers : **

- None
