### ISSUE TITLE
Add a feature to find the number of days a student need to acheive configured Attendance rate.

### ISSUE THREAD

**Issue by VarshaRajput12** [navgurukul/ghar#137]
Add a feature to find the number of days a student need to acheive their configured Attendance rate. 
Using this formula:-
step 1 : Present days=Total working days×Current attendance rate
step 2 : New present days=Total working days×Desired attendance rate
step 3 : Extra present days=New present days−Present days

**Comment by Vijay-train** [comment]
I think, this will be very tricky to implement. If we get more of this ask in the future, we can reconsider. for now, closing
