### ISSUE TITLE
Pune campus - need ways to handle specfic cases (like students being in HVA)

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#17]
Some students are part of HVA ( Hyper Verge Academy).. Need a PRD to understand how they would be handled in ghar.

**Comment by abhilashnavgurukul** [comment]
Updated student PRD. Have added wireframe document and video in the prd.
https://navgurukul.atlassian.net/wiki/spaces/ghar/pages/68550664/Student+Management

**Comment by Vijay-train** [comment]
@poojasingh1995 - Assigned to you to implement

**Comment by poojasingh1995** [comment]
Resolve the issue by creating  a form(create tag) and made the connection between student report and tag report and wrote some deluge code for validation.
