### ISSUE TITLE
Option to specify the type of degree obtained, such as B.Com, B.Sc, or B.A in Ghar Student Registration form

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#186]

**Comment by poojasingh1995** [comment]
Yesterday, I understood and worked on it and today have to push it into production.

**Comment by poojasingh1995** [comment]
Yesterday I added more options in the qualification field and also Bala wanted to add a text field so that if there is any new qualification it can be added, so I added that.

**Comment by poojasingh1995** [comment]
Last time I checked after importing it, discuss it after the scrum call today with vijay.

**Comment by poojasingh1995** [comment]
This was discussed and checked with vijay and then it was pushed into production.
