### ISSUE TITLE
Phase II Data upload (Pune, Bangalore, Udaipur, Kishanganj ) by 3rd May

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#197]

**Comment by shashi-NG** [comment]
STATUS: Delayed
REASON: As no history of donor cycle was getting maintained at the student level when the new donor cycle was update it was replacing current data. So had a call with Lakshmi and decided on having the DonorCycle History at student level on priority.

**Comment by Vijay-train** [comment]
This is done
