### ISSUE TITLE
Implement Student transfer feature.

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#20]
Student may be transfered from one campus to another. Or from on school to another. When a student is transferred, transfer history should be maintained.

Wireframe pdf:
[transfer-student.pdf](https://github.com/navgurukul/ghar/files/13213237/transfer-student.pdf)

Wireframe walkthrough video:
https://github.com/navgurukul/ghar/assets/117743777/dfd43904-874b-4714-a4d8-f8e7655ca45c

**Comment by abhilashnavgurukul** [comment]
Updated the student PRD new requirements,wireframe, and video

https://navgurukul.atlassian.net/wiki/spaces/ghar/pages/68550664/Student+Management

**Comment by VarshaRajput12** [comment]
Implemented the feature with take care of the leaves/attendance record.
