### ISSUE TITLE
Need to add a Donor cycle history in detail view.

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#209]
- [ ] Import prod data
- [ ] Students with gaps in Donor Cycle
- [ ] When student status changes other than "Active" we should automatically update the DC status as "Complete"
- [x] Tabular report, per DC, Active student count, completed student count. Active (Expired) count (Not doing this for now, we already have the bar chart that gives this info, we will relook at this later

- [x] - [x] Need to add Validation on Delete of Donor cycle and Deletion on partner.
- [x] Modify the UI.. Make only single tab and Diffrent Panels and Buttons to show all Reports (https://navgurukul.slack.com/archives/C053TRDJT5F/p1717497807831879) 
- [x] Students with expired DCs
- [x] Students with DC expiring in a week
- [x] Show all students
- [x] in Add_Student, Donor_Cycle_Start_date and end date should be lookuips
- [x] Add student names in all reports
- [x] In all reports, on clicking a record, launch the student details view
- [x] Count of students who dont have any DC assigned ( that is the subform is empty), backed by a tabular report
- [x] [Need to provide permissions to Donor Cycle.

- [x] - This error "Assigning date must be between the start date and end date of the donor cycle." should also list the start and end date of the donor cycle

**Comment by VarshaRajput12** [comment]
- I wrote the script to for making the donor cycle "Previous" when we mark the student as Dropout. here , We are getting an issue while marking the students dropout the donor cycle are getting "Previous" but it is creating the new entries as well which should be created while we make the status as "Active".

**Comment by VarshaRajput12** [comment]
- We imported and tested the Dnonor cycle sheet in which have to reimport the sheet and make sure that the donor cycle 1 would store as a history, so while import it is not working so I wrote a funtion to make make the last donor cycle as history.
- Will show and ask Vijay and Shashi that we should made the donor cycle as history like that or not,, and will work accordingly.

**Comment by its-nasir** [comment]
Date :- **16/05/2024**

I imported DMS sheet data into ghar-DMS to check if the History record feature is working. I also tried adding campus details in the donor cycle field on the Add Student form, but it isn't possible at the moment. Varsha and I are currently investigating how to enable this feature.

**Comment by VarshaRajput12** [comment]
- I wrote a function "MakeDonorCycleAsPrevious" to make the exixting donor cycle as previous. here we are not able to get the existing donors to update. 
- Will Coordinate with Vijay regarding this.

**Comment by its-nasir** [comment]
Date :- **17/05/2024**

Worked on Donor Current and Previous Show in History as Vijay mentioned in the co-working call. We are currently unable to access donor cycle field values and are working on resolving this issue.

**Comment by VarshaRajput12** [comment]
- Wrote the deluge script for making the multiple records as Previous. now we are able to make the multiple records as previous.
- Will show Vijay and Shashi and then will work according to their feedback.

**Comment by its-nasir** [comment]
Date :- **18/05/2024**

We created a workflow for maintaining donor history in the student detail view, allowing for the editing of bulk donor data. Additionally, we added a field in the donor cycle form for "Campus-Duplicate" to store the current campus when adding a student donor cycle.

**Comment by VarshaRajput12** [comment]
- Worked on the Try-Catch Schedule task.. and then implemented the Donor cycle history feature into the "Ghar".
- Nasir and I will test the feature by importing the data and after getting the reviewd by Vijay , will as o push into theh production.

**Comment by its-nasir** [comment]
Date :- **20/05/2024**

Worked on Slack notification and tested some donor changes(bulk import and transfer) feature.
We will be pushing all the COG_DMS changes into ghar and testing them.

**Comment by its-nasir** [comment]
Date :- **21/05/2024**

We tested DMS changes and fixed some bugs (like multiple data import and adding campus names in the donor cycle history view). After reviewing everything with Vijay, we pushed all the donor changes to production. Now we want to import all the campus donor sheets into DMS.

**Comment by VarshaRajput12** [comment]
- Tested the Donor cycle feature in the "Ghar" by importing the data and resolved the minor issues those were occured.

**Comment by its-nasir** [comment]
Date :- **22/05/2024**

I updated the DMS sheet format, resolved previous donor history issue with Vijay's , and discussed the Donor/Student StartDate and EndDate for (DMS) with Shahi and Vijay.

We are now going to import all the DMS campus sheet data into production.

**Comment by VarshaRajput12** [comment]
We updated the DMS sheet format, resolved previous donor history issue with Vijay's , and discussed the Donor/Student StartDate and EndDate for (DMS) with Shahi and Vijay.

**Comment by VarshaRajput12** [comment]
- Yesterday, after Scrum I and Nasir updated the remaining campus sheet and after that we had meeting with Shashi regarding the Donor cycle Start and end date.

**Comment by its-nasir** [comment]
Date :- **23/05/2024**

I tested all the import scenarios with Varsha and discussed the donor history start-date and end-date format with Shashi. currently working on it.

**Comment by VarshaRajput12** [comment]
- tried to Implemented the start date end date logic as Shashi suggested after that we had meeting with Vijay and Shashi regarding this start and end date issue so we explored about it that what is the simplest way to achieve this. will continue working on it.

**Comment by VarshaRajput12** [comment]
- Created the subform and wrote some deluge script to auto populate the start date and end date of the donor cycle..
- Will add some validations, after that will test it properly will ask Vijay and Shashi should we keep this implementation or not

**Comment by its-nasir** [comment]
Date :- 27/05/2024

We discussed about date form and userflow with shashi and vijay ,Need to connect with varsha and try to import bulk data in DMS new date changes.

**Comment by its-nasir** [comment]
Date **28/05/2024**

We made changes to the DMS sheet format and imported data multiple times for testing. We also added validations to the donor cycle subform and the donor history form.  need to discuss the new format sheet data with Shashi.

**Comment by VarshaRajput12** [comment]
- Nasir and I added the validations and prepared the new formatted sheet and tested it..
- Get to know a bug in which on the edit on the donor cycle the cycle name is getting added to it which should not happen, after that will prepare AMS sheet for Udaipur.

**Comment by its-nasir** [comment]
Date :- **29/05/2024**

I wrote a workflow for auto Validate EndDate Based On status but there is some issue that needs to be fix and testing some import parts, after completing this we need to do e2e testing.

**Comment by VarshaRajput12** [comment]
- Prepared the AMS sheet for Udaipur, tested it and resolved the errors. 
- Will Import the Udaipur AMS sheet into production after that will ask Vijay to review the Docor cycle feature.

**Comment by its-nasir** [comment]
Date :- **30/05/2024**


We tested DMS scenarios and coordinated with Vijay and Shashi on some flow points. We also fixed the autoValidateEndDateBasedOnStatus condition, but now we need to modify it. I need to work on finding the student day count in the donor cycle, as discussed with Shashi yesterday.

**Comment by VarshaRajput12** [comment]
- Had meeting with Vijay ans shashi and worked on the changes as they suggested.
- Will work on the implementation to track the gap of donor cycle for any student.

**Comment by its-nasir** [comment]
Date :-  **31/05/2024**

I worked on (studentSpentDay'sInDonorCycle), but there is an issue with the workflow. Today I will fix it.

**Comment by VarshaRajput12** [comment]
- Coordinated with Kajal regarding the Attendance tasrting date field and worked on the implemention for the Days calculation of students in each donor cycle.

**Comment by its-nasir** [comment]
Date :- **1/06/2024**

We discuss some scenarios of (student spending day’s per donor cycle) with shashi and fix it. Currently I'm working on finding a date gap between donor cycles.

**Comment by VarshaRajput12** [comment]
Imported the Bangalore data in production then wrote the deluge script to calculate the days for each student in each donor cycle, and made the changes to add the Bangalore AAs and CAs for slack msgs.

**Comment by VarshaRajput12** [comment]
- Tried to wrote the logic to get he Duration in which students do not any Donor Cycle.

**Comment by its-nasir** [comment]
Date :- **2/06/2024**

Working on student duration where the student is not present in any donor cycle.

**Comment by VarshaRajput12** [comment]
- Yesterday I and Nasir made the Donor Cycle changes in Ghar..
- Will do testing and then will check about the Frappe integration.

**Comment by its-nasir** [comment]
Date :- **5/06/2024**

I removed all the donor changes in dev-copy and we added new donor changes into ghar, also yesterday i added (Validation on Delete Donor cycle), now i will work on (Students with gaps in Donor Cycle) notification pending task.

**Comment by VarshaRajput12** [comment]
- Yesterday we made the remaining changes some validations and tested the Donor cycle feature through importing the data and all, after that had meeting with Vijay he reviewed it and suggested some changes so we made that..
- Watched some videos related to Frappe didn't find anything helpful so will continue with this, will search how we can create APIs.

**Comment by VarshaRajput12** [comment]
- I and Nasir Coordinated with Vijay and ade the Donor Cycle changes,added some validation and pushed the changes to Production.
- We will try to complete the "Students with gaps in Donor Cycle" task.

**Comment by its-nasir** [comment]
Date :- **6/06/2024**

- Yesterday we did some note(tasks) changes into ghar and pushed to prod.
- We will work on the Gap Donor cycle. If the sheets are ready, we will import all the sheet data to production.

**Comment by its-nasir** [comment]
Date :- **7/06/2024**

Worked on (Donor Date Gap ) function after reviewing the code and discussing how we are executing the Donor Gap function then vijay will push to prod, I will take a new notification task.

**Comment by VarshaRajput12** [comment]
- Worked on " When student status changes other than "Active" we should automatically update the DC status as "Complete" this issue need to do testing.

**Comment by its-nasir** [comment]
Date :- **11/06/2024**

Today, I will think about new logic of (gap donor cycle) and work on it.

**Comment by VarshaRajput12** [comment]
We have created the separated issue for remaining items.
