### ISSUE TITLE
Slack message for users missing LP

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#210]
Student (Active) who have one more LP user names missing.

**Comment by kajal8512** [comment]
Need to work on to whom we can tag for this notification.

**Comment by kajal8512** [comment]
I Need to discusse with vijay- how to get only for those campuse who has the programing students.

**Comment by kajal8512** [comment]
I made changes to this notification; I need to modify the message.

**Comment by kajal8512** [comment]
Need to do changes in the notification - and have to decied the how to handle this for campuse wise - which campus has  schoold of programming.

**Comment by Vijay-train** [comment]
This is fixed
