### ISSUE TITLE
Deployment of Speak & Improve

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#215]

**Comment by poojasingh1995** [comment]
Waiting for vijay's review.

**Comment by poojasingh1995** [comment]
It is in production.

**Comment by poojasingh1995** [comment]
Yesterday I worked on importing speak and Improve data and coordinated with ragina regarding banglore campus. 
Today I will coordinate with the team regarding write and improve data entry and will help them in that.
