### ISSUE TITLE
Sharing with campus team ( and helping them not need campus sheet anymore) - Speak & Improve & Write & Improve

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#216]

**Comment by poojasingh1995** [comment]
Yesterday I worked on importing speak and Improve data and coordinated with ragina regarding banglore campus.
Today I will coordinate with the team regarding write and improve data entry and will help them in that.

**Comment by poojasingh1995** [comment]
Today i will continue this and will coordinate with vijay regarding campus field.

**Comment by poojasingh1995** [comment]
I had a call with all the campuses yesterday and explained the whole process to them, cleared their doubts and after that I saw the notification issue.
Today I will connect(help) with Dharamshala regarding data entry, after that I will also connect with Delhi campus.

**Comment by poojasingh1995** [comment]
Last time I got a bug regarding data entry of Write and Speak Improve, I resolved it, and worked on the notification with samiksha, after that I created a Google form.
Today I have one more bug, in Write and Speak Improve it is allowing duplicate entry, so I will write the work flow for that and send the Google form to the team, if I get more time, I will reschedule the notification again.

**Comment by poojasingh1995** [comment]
Yesterday I worked on the workflow for duplicate entry and created a feedback form and imported the campus sheet.
Today I created a video regarding duplicate entry and reviewed the feedback form with Shashi and sent it to the team. Will also coordinate with Samiksha after notification regarding. and will join the Baithak session with the team.

**Comment by poojasingh1995** [comment]
I followed up some campuses data (dantewada,delhi,sarjapura) is left

**Comment by poojasingh1995** [comment]
Co-ordinated with jashpur campus to speak and improve issue of data levels. after the data was imported, the grade levels were not getting update today I have to asked the team for the list of students whose data is facing problem.

**Comment by poojasingh1995** [comment]
yesterday I coordinated with Sakshi. In her system, the speak and improve levels of some students were not getting updated but they were getting updated in my system, and I checked it with varsha too and it were getting updated, so I suggested to Sakshi to refresh it and use it, if it's not updated after two, three days then let me know.

**Comment by poojasingh1995** [comment]
Last time I checked with varsha, today I have a meeting with sakshi and another team member from jashpur campus, I check in that meeting this issue is happening with her also or not

**Comment by poojasingh1995** [comment]
Regarding the issue which Sakshi was facing, I connected with another team from Jashpur campus yesterday and checked, the issue was only being faced by Sakshi due to her internet and laptop, hence it got resolved, but at that time Sakshi mentioned one more issue that the grade levels of the students have been imported wrongly, so I have asked for the list from Sakshi along with the grade levels of those students.

**Comment by poojasingh1995** [comment]
Regarding this first I will co-ordinate with sashi and waiting for the list who gave me sakshi form jashpur campus.

**Comment by poojasingh1995** [comment]
Today i will correct the speak and improve data of jashpur campus.

**Comment by poojasingh1995** [comment]
All the data of Speak and Improve of Jashpur campus is fine. I have doubts in two records. I will clear them and inform the team as well and will inform the rest of the campus team for checking.

**Comment by poojasingh1995** [comment]
The data of jashpur campus has been fixed, the other campuses did not respond so I am closing this issue.
