### ISSUE TITLE
Moodle implementation

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#225]
- [x] *Details view page: Show all needed data in Students details view.
- [x] In Module add completion flag. Make the display text as "Completed?"
- [x] In production, run the 400-2000 range across functions
- [x] Set the schedule timing 
- [x] In prod, check that the data is coming correctly, fix any bugs
- [x]     * Ghar internal page - need to update data in manage learning page
- [x]     * Create a test plan , and test all scenarios (like some act complete, some topics completed, courses not setup properly etc)
- [x]     * Everything working and tested on server1
- [x]     * Only get info or store for a particular curriculum
>  * Slack messages (List each of them here)
- [x] Number of students <*progress*>.
- [x] We need a message that lists the course that are not meeting ghar criteria ( like not having min/max duration or not having summative assement or not having course completion criteria etc)
- [x] Students - some signal that they are not on track ( need to brainstorm more)
- [x] Students- who have not accessessed a course for a while? 

 > nodejs issues

- [x] Return only counts for activities except announcement forum 
- [x] Topic completed data issue 
- [x] Clean up all unnecessary code and functions. in nodejs
- [x] ProgressAPi is returning "sept" instead of "sep" , this is breaking zoho logic. 
- [x] Move to fetchning users by userid rather than their email.

- [x] Detail View Issue (pause)
- [x] Run the moodleinternalform for students range with student ids  for all functions
- [x] Create reports for Slack message
- [x] Update the Slack message for only displaying 10 students' data.
- [x] Update code for Start date 
- [x] Testing with Scenarios
- [x] Push the changes in production for Progress code used to slack notification.

**Comment by ujjwal15718** [comment]
16 May - The Moodle server is not running, The MySQL service is not show in the instance, why this is happening this need to debug

**Comment by Goldy2488** [comment]
- Coordinated with moodle team then worked split the function for run the all code for specific range in internal moodle form.

**Comment by jyoti9909** [comment]
Slack msg reports had created for two slack messages.
WIll test by manual data on Missing Last access date in reports.

**Comment by ujjwal15718** [comment]
Fixed the moodle server [database issue] with Amit, server is running now
There was an issue with the firstActivity complition date, that data passed in the topicAndActivity api
coordinated with Poonam and Rupa, the missing data of the student and their partner Id

**Comment by jyoti9909** [comment]
- Rename the slack message report [Jyoti sharma](mailto:jyotisharma@navgurukul.org)
Non - engaging overview
Student failing back

- Slack message data has to verify
- Module and topic me reduce fields (total Activity ,total topics,completed topic ,completed  activities) activity completion rate
- Check slack report Report 
- Recheck : Schedule function me 200 range to 100

- Min max duration reduce columns as one column only (working today)
- Testing with @Goldy2488

**Comment by Goldy2488** [comment]
we worked on 
- History page data curriculum id - some data are why missing
-Did changes for Start date 
-Remove current detail view
-Hide Summative assessment black
-Clean up code and report with @jyoti9909 
I will do testing with @jyoti9909

**Comment by ujjwal15718** [comment]
Trying to implement the docker in the server for both dev and prod

**Comment by Goldy2488** [comment]
We worked on : 
   - Clean up all functions and reports with vijay and jyoti sharma.

**Comment by jyoti9909** [comment]
- Yesterday we do the renames of columns and do updates for rename columns like min-max duration and all.
- We also do the update in code for formatting 
-We also do the cleanup for some function

Today we will continue with dev and prod environment setup 
WIll discuss with team I have some doubt regards yesterday update for code.

**Comment by ujjwal15718** [comment]
coordinated with moodle team, And fix the issue in topic Api from node, an error was facing by moodle team when inside topic activity get missing, debug the issue and fixed it and again tested with team moodle feature

**Comment by jyoti9909** [comment]
Yesterday we Find a bug in our topic code during the testing then we werer try to debug the code and we got the final output.
I also fixed the issue in updateallMoodle data code. Rename the button and Add student form field which is uses to display the moodle data on manage learning page.
We also tell the moodle criteria issue to vijay and they tell team to set that criteria and we do testing after that.

Today:
We going to cross check the data and last day some students data is not coming on ghar so we also have to check that issue.
So this task will go with the help of goldy. She will check on ghar and I will check with moodle data.

**Comment by Goldy2488** [comment]
Completed :
Upcoming:


and further work coordinate with moodle team.

**Comment by ujjwal15718** [comment]
In topic api, startDate is passing to the zoho side but the date is not going proper for some user who completed the task on same days, fixed the issue and then tested with team

**Comment by Goldy2488** [comment]
Completed :
 - update the curriculum progress field 
Upcoming:

we will test the data correction and if any find error then we resolve it.

**Comment by jyoti9909** [comment]
Yesterday we  have to check the data which comes on production so we find out the issues. There we find 4-students who are not have their data on production and why?
We find that start date is issue in this which was I thought it was issue from the moodle server but not it was from node js. But on moodle server there is something happening with module 3 course. 
So I co-ordinate with sajan and tell them. She will tell me today about that.
Yesterday during the testing we find an issue with submative average on module level. So ujjwal will check the node code then we will fixed it.

Today:

We will check once again production data and will check the start date again and match it with moodle again. 
Will co-ordinate with team and discuss about the average.

**Comment by ujjwal15718** [comment]
The average percentage was going wrong, it is fixed now by calculating only summative assessment marks 
Need to check why course duration API not perform well, that get failed during scheduled function

**Comment by Goldy2488** [comment]
Completed :
 - worked on slack Moodle messages 
   
Upcoming:
- we will find the reason why progress api is not working for 1-100 range.

**Comment by jyoti9909** [comment]
Yesterday we set the slack msg code for last access student.
Yesterday we cross check the result fro nodee js to moodle for avg percentage.
Yesterday we discuss with sajan about the activity which has not completed msg.
Today we will check the data on production.

**Comment by Goldy2488** [comment]
Completed :
 -  Worked on progress api issue then with moodle team we resolve it 
 
Upcoming:
 - we will work on handle the criteria related update in zoho then work on slack message .
 - after completed the task coordinate with vijay for pushing changes in prod.

**Comment by jyoti9909** [comment]
Yesterday we setup progress API chnges to code.
Update slack messages.
Today we will resolve the isssue which we are facing previously in module code.

**Comment by ujjwal15718** [comment]
The progress API takes time, I stopped the API and the same things were sent into course API
update in topic API and send the message where course criteria are not set

**Comment by ujjwal15718** [comment]
spend time with the Moodle team, testing the Moodle features, updating node code status will show true if the general topic has only an announcement forum, testing with the team, coordinating with Sajan, testing on Moodle criteria set issues

**Comment by Goldy2488** [comment]
we worked on handle the criteria related update in zoho the after completed the task coordinated with vijay for pushing changes in prod.
i will Coodinate with @samiksha-pattir regarding the notification issue.

**Comment by jyoti9909** [comment]
Yesterday on working day we do testing and found issue in avg perentage calculation of all modules. So we had tried to resolve it. 
Then we co-ordinate with team and discuss all the codes for push in to production.
We also co-ordinate with sajan, she had some queries regard set the completion criteria for module for new activity. 

will work on the same for course completion criteria setting and we had some ideas but not fully so we have to work on it. To resolve the moodle doubt.

**Comment by ujjwal15718** [comment]
spend time on investigation and call with team, planning to track test submitted time, if the completion date is missing need to discussed more upon this topic, And today going to look the node code if we will track the submitted time

**Comment by jyoti9909** [comment]
Spend time to investigate how to resolve the moodle issue. We were tried different methods but we were not gett any desired output. By searching we found that there will no other way to change the activity completion criteria. But we get something useful. We will keep trying with same.

**Comment by ujjwal15718** [comment]
investigating on Moodle about the start date missing till not do mark as done, after reaching a solution started to check the node code that can modify the code, And couple of meetings attended

**Comment by Goldy2488** [comment]
coordinate with moodle team then accordingly i pickup task and also coordinate with @samiksha-pattir regarding the notification task.

**Comment by jyoti9909** [comment]
Yesterday We were trying to get the completion date and wants to avg of grades become with the min grades by some calculation. So we were searching the min grades fixing but I found if we change it so we have to change it in site admin settings. It means that if we change the min grade than it will apply for all modules not for a single. 

So today we will check the node js result if it has completed and will co-ordinate with goldy regards next pick up task from ghar for moodle.

**Comment by Goldy2488** [comment]
yesterday i coordinate with @samiksha-pattir  and vijay regarding the notification code and days spend in campus code pushing into the production then worked on updated the schedule functions and display the current module in manage learning journey page.During that i coordinate with moodle team regarding the summative assessment testing.

Today i will work with summative assessment test with moodle team.

**Comment by ujjwal15718** [comment]
investigating and testing on Moodle site with user data, found the bug in the node API for percentage, not working for multiple users perfectly, And tried to resolve the missing date issue of a user if they didn't click mark as done, it worked for one but for multiple users get fail, Need to restructure the API and update the code from node

**Comment by jyoti9909** [comment]
Yesterday I tested the data on moodle than we find that there are many activities with "mark as complete" setting. So I checked for some of them no one student marked those activity as completed. 
Then after we co-ordinate with ujjwal and describe them what is happening on moodle. I also co-ordinate with goldy regards ghar forms and repoerts. We find the issue on avg percentage.
So today will co-ordinate with ujjwal regards data on server.

**Comment by ujjwal15718** [comment]
spend time on debugging the summative assessment percentage from node and Moodle as well update a condition data is going fine and in some activities unable to track therefore data is not matched if the criteria setting and "mark as done" issue will resolve, then data of node start to match with moodle data itself

**Comment by Goldy2488** [comment]
we spend time on summative assessment percentages with Moodle team then did moodle changes in cog  because its not updated structure.
today I will coordinate with moodle team regarding the testing then worked on slack message(student not attempt any activities).

**Comment by jyoti9909** [comment]
yesterday I check the average percentage for courses for a perticular student and I found its avg is different from API so, I discuss it with ujjwal and he explaing the scenerio. There was something issue on API so he takes it to resolve and setup the API. 
We also check the activities setting scenerios and discuss it with vijay. Then we were trying to some other method to get that activity data.
Today we will work on same that how we track other new activities without unlock the course setting.

**Comment by ujjwal15718** [comment]
There was an issue that came on the status of students of summative assessment that tells whether it passed or failed, and the minimum date of activity got missed in topic API, debug the problem and fixed it as of now.

**Comment by jyoti9909** [comment]
Yesterday I tested data for setting avg percentage API data but we get something wrong on start date for module 1. By some issue we get the completion date but not getting the start date for every student. So we have checked it on moodle and we get the start date for same module on moodle. So ujjwal was trying to set this code. 
I am trying to search the way to get activity status but it was not fruitfull. So I raise query on moodle forum. So I waiting for their reply. 
Co-ordinte with goldy regards zoho for moodle. She was doing some variable method by using object method that if in case someone change the any word for progress then this will useful.

Today will co-ordinate with ujjwal regards start date. If I get the desired reply from moodle then we will apply it on moodle.

**Comment by Goldy2488** [comment]
I worked on a Slack notification that alerts students who have not attempted any activity yet. I also tried to remove certain text (such as 'behind' and 'ahead') from the code and store the result in a map.

I will do testing with Moodle team in zoho.

**Comment by ujjwal15718** [comment]
Following up the node code for the status of the student was not matched in some cases, debug the issue Also the minimum date problems going null while the date is available it was happened due to a missing condition The date is coming from Moodle undefined fixed it, And still test the changes but the date is getting same for each user, we unable to find any user in moodle whose min date is get differ for course 24, It need to check because during multiple parallelly call I want to check weather the date is take same or it will go perfect

**Comment by Goldy2488** [comment]
I will check the behind notification and find out why it goes empty.

**Comment by jyoti9909** [comment]
I was trying to co-ordinate with moodle Forum. So I do some msg to them and they replied to us on mail. They were given the appointment link. I scheduled meet but today I check the mail. I havn't recieve any appointment confirmation mail. 
I also co-ordinate with ujjwal regards avg assesment and dates. 
Today we will fix the moodle notification issue.

**Comment by jyoti9909** [comment]
Debug the progress code. Atually in this code we have to handle condition on two different places but we were using the singl condition due to which it pick up the other value and send it to slack.
Today We will co-ordinate with and asked them to modules setting and their duration criteria. Will discuss with ujjwal about activities and after that will co-ordinate with vijay.

**Comment by ujjwal15718** [comment]
spend time on Moodle backend node code, updated and merged the code that resolved the minimum date issue among all activities, tested it after merged, running fine, And might be following the scenario when criteria are not set for activity, how many things can we fetch from moodle that what we are rendering to Zoho and what need to render more if date not access by us

**Comment by ujjwal15718** [comment]
Moodle has an issue with marking as done, follow up on the Moodle issue by coordinating with Sajan, A new issue from the academic side we noticed,i.e some modules have S.A and they have more than one activity but that no need to attempt by students, discussing the pending items with team, and trying to find any solutions

**Comment by jyoti9909** [comment]
Yesterday we have to discuss the activity criteria issue with sajan. As we discussed it with sajan then she explain a scenerio where our Submittive assessment never be completed as per their requirement. So Need to find the solution or do change in testing scenerio.

**Comment by ujjwal15718** [comment]
follow up the Moodle criteria issue with the team and check the flow of code if we remove the email and start to use the userName from the node,

**Comment by jyoti9909** [comment]
Need to push the changes in production for progress code.

**Comment by Goldy2488** [comment]
yesterday we spend time on progress structure and Activity criteria related issue for that coordinate with vijay 

today also spend time on progress

**Comment by jyoti9909** [comment]
Yesterday we remoe the dependency of activities so udate the code for calculate progress on module level, curriculum level and manage learning page also.

Today we will work on notifications.

**Comment by Goldy2488** [comment]
10 June 2024
worked on progress calculation at the curriculum and Module level.

today we will worked on slack message and also will test the behind slack message data.

**Comment by Goldy2488** [comment]
I worked on the progress calculation with the jyoti sharma

**Comment by Goldy2488** [comment]
we create separate issues for rest of the task
