### ISSUE TITLE
Campus filtering should filter for "Operational" state

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#23]
In many parts of ghar, there is logic to filter campuses like below..

`allCampusData = Create_Campus[ID != null];`

Here, it only checks for null ID, but it should also check for` Status == "Operational"`

We need to search for this pattern in entire code base and update

**Comment by kajal8512** [comment]
Whereever I found this "allCampusData = Create_Campus[ID != null];" line added  there the Status == "Operational" and Whereever it is needed.

**Comment by kajal8512** [comment]
Whereever I found this "allCampusData = Create_Campus[ID != null];" line added there the Status == "Operational" and Whereever it is needed.
