### ISSUE TITLE
Need to add spend days and joining date in the dropout message 

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#231]

**Comment by shashi-NG** [comment]
![Uploading Screenshot 2024-05-02 095732.png…]()

**Comment by Vijay-train** [comment]
We need to add more context , so when we pick these issues up in future, we have all the data. 

Where does this data needs to be shown?

**Comment by Goldy2488** [comment]
10-7-24
Today, I will understand the task and then start working on it.

**Comment by Goldy2488** [comment]
I added the spend days and joining date in the dropout message.

now it is pushed in prod.
