### ISSUE TITLE
Give access only to Ghar Tickets for given Emails

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#235]
![Screenshot 2024-05-07 122336](https://github.com/navgurukul/ghar/assets/145335749/df762838-e5f1-4d63-a8e1-e5e8bb077046)

**Comment by shashi-NG** [comment]
Email ID
--
raipurcampus@navgurukul.org
jashpur_campus@navgurukul.org
dantewadacampus@navgurukul.org
sarjapur_campus@navgurukul.org
banglore_campus@navgurukul.org
punecampus@navgurukul.org
udaipurcampus@navgurukul.org
dharamshala_campus@navgurukul.org

**Comment by shashi-NG** [comment]
projectpotential@navgurukul.org

**Comment by VarshaRajput12** [comment]
I have made the required changes for this task, need to discuss some doubts with Vijay so I have scheduled a call.

**Comment by VarshaRajput12** [comment]
Didn't get anything to display the record for specific users, I have a suggetion (can we add a Pannal to show all Tickets but on the dashboard only logged in user's tickets will show) will discuss it with Vijay.

**Comment by VarshaRajput12** [comment]
this is pushed to production, I need to  confirm with Vijay and Shashi that should we add these emails directly from zoho creator or we should asked the team to login through these emails.
