### ISSUE TITLE
Adding a tag to student when they are transferred from one school to other.

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#236]
![Screenshot 2024-05-06 132103](https://github.com/navgurukul/ghar/assets/145335749/147c14a6-78a6-48d4-b7de-0d2d88059b5c)
![Screenshot 2024-05-07 133452](https://github.com/navgurukul/ghar/assets/145335749/9d727e69-2338-4261-a75d-b04900496e8a)

**Comment by poojasingh1995** [comment]
![image](https://github.com/navgurukul/ghar/assets/84632896/13cee9b5-a493-462c-bcaa-732e59dff212)
![image (1)](https://github.com/navgurukul/ghar/assets/84632896/ec28e886-6eb3-4bae-a5f9-6f9267a765e3)

This feature is already implemented.
