### ISSUE TITLE
Add API Key to 'Manage Students Detail' API

### ISSUE THREAD

**Issue by kajal8512** [navgurukul/ghar#238]
Update the Node.js function to include the API key for this API - "https://ghar.navgurukul.org/get/zoho/students?min_value=1&max_value=500"

**Comment by ujjwal15718** [comment]
20-06-2024
investigated to manage the node API to authenticate, But the approach by using jwt, session, and all needed databases still investigating and will find an approach that how we can control our api from public api to only certain users can hit or authenticate the apis
