### ISSUE TITLE
Houses in Campus 

### ISSUE THREAD

**Issue by Goldy2488** [navgurukul/ghar#285]
Document on House Structure in Campus : 
https://docs.google.com/document/d/1qbJnhOtfA7gzXA5ita_261XsR-d4blaKVtAS8IYR9Jk/edit#heading=h.65id3ilkohfs

**Comment by Goldy2488** [comment]
yesterday I understood the doc and during that, I listed the questions that I did not understand. 

Today I will coordinate with Vijay and Shashi to understand the structure.

**Comment by Vijay-train** [comment]
We are pausing this work for now
