### ISSUE TITLE
Moodle Activities Status Tracking

### ISSUE THREAD

**Issue by jyoti9909** [navgurukul/ghar#289]
- Track new activities within the setup module.

- Ensure production data is correct until the we do modification.

- Module Structure Discussion: Summative Assessment
        Summative Assessment includes three activities.
        Currently, only a single activity is used in Module 0.
        Track the completion status of the summative assessment. (Need to discuss)

**Comment by jyoti9909** [comment]
Yesterday I check new activity tracking on our develpment server. I noticed that if we change the unlock the setting then it has to show the false condition for all attempted activities but It takes time to reset  their status based on data. 

So I add a new act. in it by unlocking the course completion setting and set them. It is working if this is happening. 

I check the data on production then It missed the summative avg percentage. (Need to discuss with ujjwal)

**Comment by Vijay-train** [comment]
This is completed
