### ISSUE TITLE
Relook at Progress Calculation for Moodle

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#292]
Today progress is calcualated based on the # of activities that are completed in a Module. It can happen that students never complete some of these activities, as its not needed. For instance - a student can complete only "Basic Math" and that should be enough, and they need not complete other activites.

How do we remove the dependency on activities to calculate progress?

**Comment by jyoti9909** [comment]
Yesterday We do discussion with team regard progress calculation how we remve the dependency of activities.

**Comment by jyoti9909** [comment]
yesterday we update and check the all dependency for progress calculation code. we also create fields to do formatting. Goldy do fomattings and we find a bug in module code so we debug that code. And we also correct the display format on manage learning page. 

Today we will push the codes and will going to others.

**Comment by Goldy2488** [comment]
We worked on this, but were unable to find the finalized formatting, so we stopped working on this and started the notification task, then we'll come back to this.

**Comment by jyoti9909** [comment]
Yesterday I was working for this for formatting the message displayed on all report.Then We found some logical issue and try to final approach but not getting that so I pick the another task for slack message.

**Comment by jyoti9909** [comment]
We do some modification in names of coulumn field. So everyone understand the formatting reason for red colour.

Now its ready to push production.

**Comment by jyoti9909** [comment]
Done
