### ISSUE TITLE
Activitiy completion tracking

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#293]
When new activities are added to an existing module, they need to be explicity check marked for it to be tracked. But when this is done in Moodle, there is a warning that existing completion data might be lost. 

We need to figure out if there is data loss in such a scenario. if there is none, then we are fine. But if there is ( or if we are not sure), then how do we track activity completion.

**Comment by jyoti9909** [comment]
Yesterday we were discussed  the scenerios about tracking status of it with vijay and today we will work on this.

**Comment by Vijay-train** [comment]
We figured out that there is no data loss if new activiteis are ticked. This is not an issue anymore
