### ISSUE TITLE
Slack Notification for Not ticked Activity

### ISSUE THREAD

**Issue by jyoti9909** [navgurukul/ghar#301]
Need slack message to alert the not tracking activities.

Need to send the slack msg for all missing ghar criteria.
We need final msg for specific curriculum so that we also define all deficiencies with curriculum.

**Comment by jyoti9909** [comment]
Today we will work for not ticked activity to get slack message. Ujjwal prepared node code so we will review it today. Will work on this notification msg.

**Comment by Goldy2488** [comment]
I prepared a Slack notification, but while testing, we found an internal server error. Regarding the error, we coordinated with Ujjwal, and also while testing, we found some bugs. We have resolved those bugs.

Today, we will continue with the same task.

**Comment by Goldy2488** [comment]
for that, I will coordinate with Ujjwal and then start work on this Slack msg.

**Comment by Goldy2488** [comment]
today i will review the code from vijay then test the all scenario with the help of @jyoti9909

**Comment by Goldy2488** [comment]
Yesterday, we tested the notification and reviewed it with Vijay. The message needs to be updated for the curriculum. I worked on it, but some work remains so that I will continue with the same task.

**Comment by Goldy2488** [comment]
message formating is complete and need to coordinate with @jyoti9909 for the testing  in all scenario in moodle.

**Comment by Goldy2488** [comment]
pushed in prod
