### ISSUE TITLE
ghar.student - sign up for copilot

### ISSUE THREAD

**Issue by kajal8512** [navgurukul/ghar#303]
Provide option to signup for copilot

**Comment by kajal8512** [comment]
I worked on the detail view and then coordinated with Varsha to explain how I am proceeding. I also sought suggestions from her. Our approach involves retrieving all student data from the Ghar app and storing it in the ghar.student application. We will apply a filter to the report, ensuring that only users with login access to ghar.student can view their data. Additionally, whenever a new student is added to Ghar, a function will be called upon successful submission of the student addition form. This function will fetch all relevant data and delete old records.

**Comment by kajal8512** [comment]
14-06-24
I am working exploring how I can show the student information. created a button on a page and call a function in that button click , show the report of student information. but I am still work on the showing data on the page.

**Comment by shashi-NG** [comment]
This is done and in Production.
