### ISSUE TITLE
There was an error in execution of a custom schedule in Ghar!

### ISSUE THREAD

**Issue by poojasingh1995** [navgurukul/ghar#305]
Custom Schedule = SendWeeklyGharSummaryWorkFlow,Function name = SendWeeklyGharSummary.

**Comment by poojasingh1995** [comment]
I was only able to check this task yesterday but couldn't give it much time so I will work on it today.

**Comment by poojasingh1995** [comment]
I checked this error and also sent notification but I am not able to understand the issue, so I want to apply some info condition in the function so that the actual problem can be found.

**Comment by jyoti9909** [comment]
08-07-2024
Yesterday we pushed the moodle changes in to production and try to fix summary division issue. So I co-ordinate with varsha she explained the issue.

So today I will try to see the exact issue and will check the moodle data.

**Comment by jyoti9909** [comment]
09.07.2024

Yesterday I look into issue no. 305 and try to understand from where we get the error email for the shedule function. So I do the correction in code only now will wait for next monday to get error email.

Today will pick another issue.
