### ISSUE TITLE
Kanban Accessibility to All needed

### ISSUE THREAD

**Issue by jyoti9909** [navgurukul/ghar#31]
- Kanban Report Accessibility: Adjust the accessibility of Kanban reports to make them visible and available to all relevant users, fostering transparency and collaboration.  This ensures that users understand the task priorities and can make necessary adjustments when needed. They also get an idea how much time it will take to resolve their ticket.

**Comment by Vijay-train** [comment]
This is fixed. Verified with accessing as a portal user
