### ISSUE TITLE
 Update Code for Data Deletion scenario

### ISSUE THREAD

**Issue by jyoti9909** [navgurukul/ghar#319]
In case if module deleted or any activity or topic then we were updating the data only. So deleting scenario is not handle by our code. 

So need to update the code for deleting scenario.
As disucssion we decide to do delete the data for active student only other inactive student's data will remain same.
We need to update the schedule codes with appropriate range used in same. create the code which takes the student  Id as parameters. This function will all under all curriulum schedule codes.

**Comment by jyoti9909** [comment]
18-06-24
Today we will update the code for delete senerio for active students.

**Comment by jyoti9909** [comment]
19-06-24

Yesterday I update the code for deletion scenerio an do some updates on updateAllMoodle code.

Today will take a look into this and will push into production.

**Comment by jyoti9909** [comment]
20-06-24

I tested the things and help  goldy to cross check the data on moodle and compare with slack msg data. Yesterday i got something completed module if there is no one actiity in summatie assesment.

Today willl discuss with team regards topic api will work on update the slack msgs.

**Comment by Goldy2488** [comment]
done pushed the production

**Comment by jyoti9909** [comment]
25.06.2024
We create function to delete the specific range of curriculum report and call this function to all scheduled updatecurriculum function which helps to delete and insert the data again.

today will push and close this issue.
