### ISSUE TITLE
Update the Moodle Slack msgs Format based on campus 

### ISSUE THREAD

**Issue by Goldy2488** [navgurukul/ghar#324]
previously we send the slack messages with the emails and modules names. In this message the campus team could not identify which campus need to help for that need to review the report respective there campus.

We need to update the Slack messages based on campus on how many students need help.
Msgs List :- 

- [x] Due date Modules
- [x] Multiple Modules in progress
- [x] not yet started Moodules
- [x] Module exceed max Duration

**Comment by jyoti9909** [comment]
21-06-24

Yesterday I worked on this msg to prepare the format.

**Comment by Goldy2488** [comment]
24-6-24

i updated the  Multiple Modules in progress and Module exceed max Duration function in the copy of ghar and also  tried to find why multiple modules in progress function is not working in production. i am not able to find the reason today worked on same problem

**Comment by jyoti9909** [comment]
25.06.2024
Yesterday we update all the slack messages for the campus wise detailed format in  copy of ghar. We also check that the execution error is comes on 401-500 students at curiculum leel. But now its coming on 1-400.

So We need to help how we check it or fix it.

**Comment by jyoti9909** [comment]
25.06.24
Update all the slack msgs to production and make required changes to all functions. 
Need to add the moodle yes/no scenerio add them also in all functions. change the schedule timing. 

We were not get the multimoodlemodule slack msg due to its setting was weekly not daily. 

today need to push the changes.

**Comment by Goldy2488** [comment]
25.06.24
yesterday we moved all changes in ghar and today need to push the changes in prod

**Comment by Goldy2488** [comment]
pushed in prod
