### ISSUE TITLE
Update all curriculum schedule workflow for deleting scenario with range

### ISSUE THREAD

**Issue by Goldy2488** [navgurukul/ghar#335]
Now we are deleting complete Moodle data from ghar by calling Refine entries within the Moodle.UpdateCurriculum(1-400) which is not good practice for handling this scenario 

Need to Update all curriculum schedule workflow for this scenario for a specific range according to the same range of curriculum workflow.

**Comment by jyoti9909** [comment]
25.06.2024
We create function to delete the specific range of curriculum report and call this function to all scheduled updatecurriculum function which helps to delete and insert the data again.

today will push and close this issue.

**Comment by jyoti9909** [comment]
26.06.24

Yestererday we setup all the timings and codes and pushed all the changes to production. We also get something wrong by serer so disuss with ujjwal.

today will work on module calulation sceduled function.

**Comment by jyoti9909** [comment]
27.06.24
Yesterday I was testing the execution error but not found the exact reason for this I also want to test this delete scenerio I was testing but not fully expected scenerio was happening. we are not getting any error during produciton execution but we get the error in deelopment. which is unexpected error.

So today I will test it with the deleted scenerio what is happening or not will check this thing should not affect our data.

**Comment by jyoti9909** [comment]
Pushed into production.
