### ISSUE TITLE
Unable to cancel Apply leave Dialog

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#34]
On apply leave dialog, if I want to cancel, it does not allow. Checkout the video.

https://github.com/navgurukul/ghar/assets/117743777/ef495043-ff98-47ff-8d27-a3a5ab38998d

**Comment by abhilashnavgurukul** [comment]
As discussed in the meeting, Cancel button needs to be renamed to clear since it is clearing data. Also close button(X) is at top right corner of the the screen. It should be at the top right corner of the modal. If this is not possible add a cancel button.

**Comment by Vijay-train** [comment]
I suggest sticking with defaults. Like needing a cancel button or moving the X button is not going to be straight forward, and its not worth the effort to fix as this is not blocking any functionality and can be learnt.

Lets rename the cancel button and that should be fine

**Comment by abhilashnavgurukul** [comment]
It would enable a better user experience. I spent few frustrated minutes trying to close the dialog box. Hundreds of user would be having similar experience.

For now we can rename the cancel button. But we need to find a way to position the close button(X) correctly. Atleast for all new features we are going to deliver. Otherwise we will be having this ux in the entire product and fixing this later will be much more difficult and complicated undertaking.

**Comment by Vijay-train** [comment]
@kajal8512 - in case youhavent looked at this already - https://help.zoho.com/portal/en/community/topic/cancel-button-not-working-when-i-open-record-in-a-new-window-for-editing

**Comment by kajal8512** [comment]
> @kajal8512 - in case youhavent looked at this already - https://help.zoho.com/portal/en/community/topic/cancel-button-not-working-when-i-open-record-in-a-new-window-for-editing

I visited the URL, but I couldn't find anything useful. The discussion mainly focuses on the issue with the cancel button, whereas we need to investigate the functionality of the right cross.

I checked other websites as well, but I couldn't find anything useful. I attempted to inspect it using Developer Tools -> Application ID. I will try to add a button in the form named 'cancel form'.

**Comment by Vijay-train** [comment]
@kajal8512 - Can you update on the latest on this please?

**Comment by kajal8512** [comment]
I didn't found any thing useful this issue,

**Comment by Vijay-train** [comment]
This is not a priority. Closing
