### ISSUE TITLE
Moodle Bugs and Error Resolving  

### ISSUE THREAD

**Issue by Goldy2488** [navgurukul/ghar#342]
We get the bugs during the execution of functions in prod where the functions execute successfully but the data is not inserted properly.

**Comment by jyoti9909** [comment]
27.06.24
Yesterday I was testing the execution error but not found the exact reason for this I also want to test this delete scenerio I was testing but not fully expected scenerio was happening. we are not getting any error during produciton execution but we get the error in deelopment. which is unexpected error.

So today I will test it with the deleted scenerio what is happening or not will check this thing should not affect our data.

**Comment by Goldy2488** [comment]
we tested the all functions, and they worked properly and worked on same task

**Comment by jyoti9909** [comment]
28.06.24
we find that the issue was happening in my refineNullEntries funcntion which delete entire data. I was testing but it was not able to find the issue.

Today will check the refine null entries function why it delete whole data.

**Comment by jyoti9909** [comment]
29.06.24
I resolve this issue and pushed into production.

**Comment by jyoti9909** [comment]
01.07.24
Yesterday I facing the latop issue. So I was only coordinate with goldy and find the bug the data is not inserting properly.


So as laptop rcv I will start my work to resolve the production issue.

**Comment by Goldy2488** [comment]
1.7.24
today I will check the calculation function and find out why it is not working in prod.

**Comment by Goldy2488** [comment]
I tried to find the reason why curriculum IDs are missing at the module level, while at the topic level, 2069 entries were supposed to be inserted but only 1661 entries were inserted. I checked all the functions and scheduled workflows but I am not able to find the reason.

Today, I again spent time on this task and also coordinated with Varsha regarding the issue.

**Comment by jyoti9909** [comment]
03.07.24
Yesterday co-ordinate with goldy regard bugs issue but we were not able to find the exact reason. we find that somehow links are break up or somehow data may be deleted or not calculated.

Today I am working for the same task. Try to find out the reason.

**Comment by Goldy2488** [comment]
4.07.24
yesterday, we tried to find the issue but were not able to find the reason for that we coordinated with varsha and we assume that it happened by deleting scenario.

today we test it with deleting scenario more today.

**Comment by jyoti9909** [comment]
04.07.2024

yesterday I checked all data and try to find out the breakups where these are happenning. So I spend time and checked that and discuss with goldy tells we get each time different scenerio.

So I will today explain the whole things with kajal and try to more debug the code.

**Comment by jyoti9909** [comment]
05.07.2024
Yesterday we fixed the issue of breakup the lookups id so that we pushed into production to those changes.

Today again we get error to insert data so the data is not inserted but manually it is also working. Will see this issue.

**Comment by Goldy2488** [comment]
5.7.2024
Yesterday, we fixed the issue that occurred with the lookup ID; we resolved it.

Today, some more errors are occurring. We are looking into why this is happening.

**Comment by jyoti9909** [comment]
06-07-2024
Yesterday we get the bug in the shedule timing. We also find small bugs so we resoleed

Today will push the changes in production and will pick another task.
Need to close the issue after scrum.

**Comment by Goldy2488** [comment]
Yesterday we got bugs due to missing token in prod. also we fixed small bugs we resolved it>

today we pushed it prod. first need to test it.

**Comment by jyoti9909** [comment]
Changes pushed in to production.
