### ISSUE TITLE
Leave/Attendance improvements - Improve UX

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#343]
### - [ ] Auto Approve leaves on Apply
> Checkbox in ApplyLeaves, by default checked.
> When above checkbox is checked, Auto Approve leaves, it can eliminate the time it takes to approve leaves

### - [ ] In the Students Dropdown (across all attendance and Leave views)

> Only show “Active” Students

### - [ ] Can we default the campus to a particular user, so they don't have to choose campus everytime in all attendance/leave

> User settings
> Store the Campus value
> Use this campus as default in all Attendance/Leave

### - [ ] New Leaves Report

> Create a Leaves report, across all students and Leave types , also show total also as a column
> StudentName	TotalAll Leavess	KitchenLeave	ExamLeave  ..

**Comment by kajal8512** [comment]
I have work with 2 poin - In the Students Dropdown (across all attendance and Leave views) , I found every form where students are an dropdown, only get active students. I created a checkbox into apply leave. I will continue with 1 point to do.

**Comment by kajal8512** [comment]
I have work on how to auto approve the leave and change the button status, and tried to that but not completed yet, I will continue working on this.

**Comment by kajal8512** [comment]
i have work on point one which is completed, Auto Approve leaves on Apply,  I will coordinated with varsha and review the changes with her,  I will start working on new leaves report today.

**Comment by kajal8512** [comment]
I have completed the point 4 (New Leaves Report) created a form and a report,  created a function which insert data into this new report for total leave of particular student.  I will continue working Pont 3rd.

**Comment by kajal8512** [comment]
I am working on Apply leaves and make it approved.  when I am apply for a leave some time auto approve works some time its not working. I will continue working on it.

**Comment by kajal8512** [comment]
I have work on the total leaves function, make correction in that,  now that working correct. I will start working on point 3rd.

**Comment by kajal8512** [comment]
I have work on the user setting point , there I have create a form and with lookup, after that, I have auto populate campus based on user setting, I did this for attendance need to work with leaves. I will continue on that.

**Comment by kajal8512** [comment]
I have completed the user settings task. After this, I test every scenario with Varsha. Once everything is reviewed, I will start doing changes into ghar.

**Comment by kajal8512** [comment]
I have move every changes into ghar , created a report for total allocated leave , I will test every feature , after that i will set a call with vijay for review the all changes into ghar.

**Comment by kajal8512** [comment]
I have tested every thing varsha, where need to do changes and fecing problem correct that, I will coordinate with vijay today and push the changes into pro.

**Comment by kajal8512** [comment]
did some changes after review the code , need to push to prod today.

**Comment by kajal8512** [comment]
after review the changes I have work on that, have to create a comman function for exam leave validation and overlap , have to use on the action of button click and validation on submission.

**Comment by kajal8512** [comment]
I have coordinated with vijay push every changes of attendance and leave into production, will coordinate with ujjwal regarding schedule workflow error.

**Comment by kajal8512** [comment]
I have work on the errors , work on the gharsummary function and check why that function is giving an error,  correct that, I will coordinate with vijay and push changes which I have did yesterday.
