### ISSUE TITLE
Leave/Attendance Improvements - Improve Loadtime

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#344]
In some places across Leave/Attedance, there is a noticable delay in load. This could be because of # of leaves in Prod. We need to figure out a way to make this better/faster.

### - [ ] On clicking “Apply Leave” , there is a momentary lag, the dialog does not open immediately.

Team reported that Campus dropdown takes long, but this could be because of the above issue

### - [ ] Approve Leaves report

Take a bit of lag to load , because there are 13k records.
How do we make it fast or change the data here to have it have less data

### - [ ] “Approve Leaves Calendar View”

Do we need this, maybe it slows down page load time?

### - [ ] “Allocated Leaves” report

Takes a bit of time to load
What options are possible to make it faster ( maybe show lesser data?)

**Comment by VarshaRajput12** [comment]
I heve recored a video with help of Kajal and send and email to the zoho support team..we got response as well so will provide them the URL with edit access.. maybe we will get to know about the issue by today.

**Comment by VarshaRajput12** [comment]
Made some changes in Apply/Approve Leaves Page as Vijay suggested, now we are displaying the Leaves record on button click and the Apply Leave form is on the Page. we need to push these chagnges.

**Comment by VarshaRajput12** [comment]
We have made some UI changes and removed some reports which were not in use.
