### ISSUE TITLE
Import the missing data of Donor cycle.

### ISSUE THREAD

**Issue by VarshaRajput12** [navgurukul/ghar#345]
Import the missing data of Donor cycle.

**Comment by VarshaRajput12** [comment]
I have Prepared the sheet for Missing donor cycle and. got some mistakes so resolve it. today will test it and import it in production.

**Comment by VarshaRajput12** [comment]
Imported the missing data of donor cycleafter testing, just have some doubts regarding Amravati data so will ask Shashi and will work accordingly

**Comment by VarshaRajput12** [comment]
Reimported the Amravati data as the dates were incorrect and so after correcting the sheet I imported it. and worked on the gap task with Nasir we tried to made the changes as Shashi suggested but they were not achiveable so will discuss it with him. to update the gap data manually.

**Comment by VarshaRajput12** [comment]
Need to discuss with Shashi.

**Comment by VarshaRajput12** [comment]
Yesterday, we corrected some data in report itself, but for sheet we  need to discuss it with Shashi and Laxmi.

**Comment by VarshaRajput12** [comment]
Fiilled the "Partner MGT Sheet" for missing days.

**Comment by VarshaRajput12** [comment]
Upadated all the Missing donor days daya for all the Active students, Today wil continue this and will of those students whose Placed and Dropout date is given.

**Comment by shashi-NG** [comment]
Done all imports
