### ISSUE TITLE
Attendance data search by full name not working

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#35]
When searching using full name the attendance data returns zero results.

Checkout the video - 

https://github.com/navgurukul/ghar/assets/117743777/e66e69c8-7746-4991-b310-c6f9a0ea572d

**Comment by abhilashnavgurukul** [comment]
As discussed in the meeting, Cancel button needs to be renamed. Also close button(X) is at top right corner of the the screen. It should be at the top right corner of the modal. If this is not possible add a cancel button.

**Comment by Vijay-train** [comment]
We have more than 1000 students and perhaps other dependencies on this field. Do you think it worth to change this field type and migrate all the existing names? @kajal8512 ?

**Comment by abhilashnavgurukul** [comment]
We need not change/migrate the data model/fields. Find a way to search multiple fields. May be via script or someother way. As data grows this will be useful functionality for faster retrieval of data. Do checkout this link as well - https://help.zoho.com/portal/en/community/topic/lookup-with-multiple-field-information

**Comment by kajal8512** [comment]
> We have more than 1000 students and perhaps other dependencies on this field. Do you think it worth to change this field type and migrate all the existing names? @kajal8512 ?

If it is not possible, then we can go with the first option.
- 1. Utilize alternate fields, such as Gmail, for searching purposes.

**Comment by kajal8512** [comment]
I put the request on zoho creator form for the help.

**Comment by kajal8512** [comment]
I got respones from zoho creator supporters - This the actual behaviour in Zoho Creator for the searching last name and first name.

**Comment by Vijay-train** [comment]
Based on our discussions, closing this issue, will reopen
- If we hear more from our users and the suggestion of searching on other fields is not adequate
