### ISSUE TITLE
Map https://ghar.zohocreatorportal.in/ to https://ghar.navgurukul.org

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#36]
Ghar application needs to be mapped to Navgurukul sub domain instead of zohocreator sub domain.

**Comment by Vijay-train** [comment]
This is a known issue. We can move it to NG subdomain but would require work.

Unless there is a functional reason to do so, suggest to not fix this

@abhilashnavgurukul ?

**Comment by abhilashnavgurukul** [comment]
Not a priority but we need to do this some time in future. But we have to keep this issue open. Reasons to do this:

1. ghar.navgurukul would be easier for the users to remember. 
2. When we share the link to external user/client/partner we should share with navgurukul subdomain. This would reinforce navgurukul branding. 
Right now we are marketing zoho products for free. Why to market zoho product free of cost? Zoho doesn't provide free access to its product or services.

**Comment by Vijay-train** [comment]
Both reasons are valid, but not worth the effort do this now. We can close this and reopen when we think it meets the bar
