### ISSUE TITLE
W/I & S/I Improvements

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#362]
- [x] KT from Pooja
- [x] Diagnose the System and look for bottlenecks.
- [x] Recommend Improvements
- [x] Implementation
- [x] Need to Create a function to get the Campus wise W&I data for each month.
- [x] After getting the data we should import the Missing data.
- [x] Provide a view access to report of W/I & S/I for help AA filter report by Campus, Month, Grade, Student Status: Active, placed, etc.
- [x] Provide a direct access to Grade Input Form 
- [x] Provide a field in form - Exam Status - Options: Present in Exam, Absent in Exam
- [x] Auto set the campus as per the AA campus preference

**Comment by VarshaRajput12** [comment]
Had meeting with Pooja she Explained all the process how we are adding the data the calculation which is happing.. I have checked the data in "Speak & Improve Report" and "S & I Notification Data Report" the data is incorrect, I need to discuss it with Vijay and Shashi.

**Comment by VarshaRajput12** [comment]
Will start working on this task.

**Comment by VarshaRajput12** [comment]
Wrote a function to get the Campus wise W&I data for each month. i'm able to get the campus wise just need to add some changes so will able to get month wise as well. and then checked the "ManageWriteImporveParticipationData"  "SendParticipationSummaryForWriteImprove" function for finding the error, i checked the workflow, here "lastWSData" this is getting empty , not sure why this is happening maybe if the data will be correct then this will also correct.

**Comment by VarshaRajput12** [comment]
Yesterday I completed the function "GetWAndICampusWiseData" and we are getting the Campus  and month wise W and I data, but have some doubt need to test it more, and I created a form to update the "W & S Notification Report" data for specific date, it is also not working as expected so will check the "ManageWriteImporveParticipationData" because this function is getting used to update data in this report.

**Comment by VarshaRajput12** [comment]
Yesterday, I updated the "SendParticipationSummaryForWriteImprove" and tried to updated the data "W & S Notification Report" using the Form "UpdateWAndINotificationData" which I have created, from this data is updating correctly but in the function "GetWAndICampusWiseData" not showing the correct data need to discuss it with Vijay will schedule a call with him, before that will coordinate with Goldy regarding this.

**Comment by VarshaRajput12** [comment]
Made the changes in "SendParticipationSummaryForWriteImprove" function and tested the data now "W & S Notification Report" is getting correct data based on "Write & Improve Data Report", and we are gettind the Campus wise data for every month form "Write & Improve Data Repor" using "GetWAndICampusWiseData" function, just need Vijay to review it for which I have schedule a call.. after that will work accordingly.

**Comment by VarshaRajput12** [comment]
Yesterday I modified the implementation for getting the notification data as Vijay suggested, we won't use a separate report to store the 2 months data, I did that for W&I .. today will do the same for S&I.

**Comment by VarshaRajput12** [comment]
I have made the changes for S&I, created a function to get campus wise data for each month (GetSAndICampusWiseDataForEachMonth) and made the changes in existing function SendParticipationSummaryForSpeakImprove.. Today will test it properly and I have schedule a call with Vijay to review it after that will work accordingly.

**Comment by VarshaRajput12** [comment]
Tested all the changes of W&I and S&I and made the changes as Vijay suggested.. today I have scheduled a meeting to review and push to production after that will work accordingly

**Comment by VarshaRajput12** [comment]
Goldy and I tested all the scenarios in W&I and S&I and resolved the issue in which all the statuses type campus students were calculated. I have scheduled a call to push these changes..
After that I will inform the campus team about the data and if needed, I will coordinate with them.

**Comment by VarshaRajput12** [comment]
Changes are pushed to production and I have created the Docs for W&I and S&I to display the data to the team and inform them to add the missing data. I have scheduled a call as well to see the process how they are adding the data and why they need to create sheet for it.

**Comment by VarshaRajput12** [comment]
had meeting with Campus team they had some doubts regarding W&I and S&I and did some changes and Investigation for resolving there doubts, and need to discuss about the "Options: Present in Exam, Absent in Exam" options. and campus field with shashi.

**Comment by VarshaRajput12** [comment]
Made all the changes as we discussed (Show all the students report for W&I and S&I and the form) so the user can see the data as needed and just testing is remaining so after testing will ash shashi to push these changes then will start working on issue 385

**Comment by VarshaRajput12** [comment]
Tested all the scenarios after making the changes and had meeting with campus team to know about the grade showing report for "Current grade value" so made the changes for storing the grade in this column but that is not done yet, will try to complete it today.

**Comment by VarshaRajput12** [comment]
These changes are complete we have tested it and pushed it in production.
