### ISSUE TITLE
Donor Management UI Improvement 

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#385]
- [x] Panel to show Total number of Active Students in NG Support Support Cycle for the current Year.
- [x] Graph to show Campus wise number of Active/Placed/Dropout Students in NG Support Support Cycle for the current Year/Past Years
- [x] Derive a proper naming for Donor Cycle
- [x] Report in which the students count will be displayed under the donor cycles for every year.
- [x] No.of students under NG support cycle should show 83 ( Kishanganj and Jashpur) - It is including the completed cycle as well - we need to rectify that( also - it is not accurate) .  As Under NG support - there should be students from Pune, Sarjapur, Jashpur, Kishanganj(until we get a donor), Dantewada and Dharamshala - The count should be close to 280-300.

**Comment by VarshaRajput12** [comment]
Made the report and added the panel which is needed but the required data is not visible, I didn't get a way to get the data which is needed, will coordinate with Goldy regarding this.

**Comment by VarshaRajput12** [comment]
Made the required changes and created the report and the panel with details which were needed, only testing is needed so will test it and then will work accordingly.

**Comment by VarshaRajput12** [comment]
I made changes for "Panel to show Total number of Active Students in NG Support Support Cycle for the current Year." data and tested it after We have meeting with Shashi he suggested some changes so will work on those UI changes

**Comment by VarshaRajput12** [comment]
Had meeting with team and didn't spent much time on this just did some investigation how we can get the required data, and how we can make the reports.

**Comment by VarshaRajput12** [comment]
made the changes to get the access of Donor cyles and students count from the Partner report in which I am able to  get the donor cycle access and for students I Have wrote a function for getting the count need to test it. and will coordinate with Goldy as well for  testing.

**Comment by VarshaRajput12** [comment]
Made all the changes and did the testing and had meeting with Shashi fir review.. today will push the changes then will work accordingly.

**Comment by VarshaRajput12** [comment]
After testing we have pushed the changes to production, in prod there were an issue in which the "Active students in Current NG support" report is not getting created, So resolved this error.

**Comment by VarshaRajput12** [comment]
Shshi will share the updated names sheet then will update all the names in system

**Comment by VarshaRajput12** [comment]
Coordinated with Nasir and reviewed the Donor changes, after that the issue which Laxmi shared, we discussed it with Shashi and I checked the workflow in which we are calculating the students count in NG support donor which is not working properly so will continue working on it.

**Comment by VarshaRajput12** [comment]
Checked the flow for getting this report, and tested in Dev but in dev the report data is correct, Investigated why it is not working in prod but didn't get anything, will continue working on it.

**Comment by VarshaRajput12** [comment]
Investigated about the issue which we were havng the "Students In Current NG Support" report and got the reason which I need to discuss with Vijay soo scheduled a call after that will work accordingly

**Comment by VarshaRajput12** [comment]
After having the meeting with Vijay i made the changes as he suggested to get the current year NG support cycle students data. after that Nasir and I  discussed and investigate that how we can create single NG support for all the  campuses

**Comment by VarshaRajput12** [comment]
had meeting with Vijay and after testing he pushed the changes to prod after that I executed the function and checked the data in prod her is and issue the report "Students In Current NG Support" is showing only Active students data so need to discuss it with Vijay that do we have to change this or not.

**Comment by VarshaRajput12** [comment]
The issue in which "Students In Current NG Support" report is showing only Active students data, I have discussed it with Vijay and made the changes aas he suggested, so will ask Goldy to review it then will schedule a meeting with Vijay to push it in prod.

**Comment by VarshaRajput12** [comment]
Coordinated with Goldy to review the changes, now I have scheduled a call with Vijay to review the changes and push to production.

**Comment by VarshaRajput12** [comment]
After discussion with Shashi I coordinate dwith Nasir and Helped him to change the logic for getting the student count for each Donor cycle and for each status.

**Comment by VarshaRajput12** [comment]
Had meeting with Vijay and Shashi, will need to investigate how we can mpdify the existing flow so we can craete a single NG support for all the campuses.

**Comment by VarshaRajput12** [comment]
Coordinated with Nasir we discussed the possible ways and Issues to select multiple campus for NG support cycle.

**Comment by VarshaRajput12** [comment]
Coordinated with Nasir to discuss the flow to make the Single NG support, he made the changes so today will test the flow is it working or not, and where it will affect will check.

**Comment by VarshaRajput12** [comment]
tested the donor chnages we can create signle NG support and update it with  old NG support for students.

**Comment by VarshaRajput12** [comment]
Had call with Shashi and we show them the progress, and he explain the further requirements in which we have implement the the feature in which we can get "Job Readiness" students so will work on this.

**Comment by shashi-NG** [comment]
done
