### ISSUE TITLE
Create Ghar application training videos 

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#40]
For effective usage of Ghar app proper training needs to be imparted to everyone who would be using the Ghar app. In person training to everyone would be impractical. Having bunch of essential training videos would help everyone to get trained at their convenience.

Create training videos on following Ghar features - 

- [x] How to onboard student? - @poojasingh1995 
- [ ] How to create, update campus/School and assign school? - @VarshaRajput12 
- [x] How to Apply leaves? - @poojasingh1995 
- [ ] How to mark student's attendance? - @VarshaRajput12 
- [ ] How to manage leave types and holidays? - @poojasingh1995 
- [x] How to use calendar/dashboard? - @poojasingh1995 
- [ ] How to create tickets? - @jyoti9909
- [ ] How to apply Compensatory Attendance? - @poojasingh1995 
- [ ] How to Update Multiple Record? - @VarshaRajput12 
- [ ] How to use Assigning Tags feature? - @poojasingh1995 
- [ ] How to use Transfer Student feature? - @VarshaRajput12 

Tick each task on completion.

**Comment by Vijay-train** [comment]
Closing this for now. Its hard to keep them in sync
