### ISSUE TITLE
Feature to bulk apply leaves

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#41]
Recently many students had gone home for celebrating diwali. Everyone had applied for 7 to 10 days leaves. However, most of the students didnot return on time. The campus associates now has to apply unapproved leave for all the students one by one. 

A feature is required where they can bulk apply leaves for student.

**Comment by Vijay-train** [comment]
We decided to not do it for now. Will do, if we hear more feedback
