### ISSUE TITLE
Slack Message : Improve the Missing Attendance Slack message

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#42]
The Missing attendance slack message that is sent every monday, lists the campuses that had missing attendance for the previous week ( Monday - Saturday)

For eg
>:scream_cat: You missed taking attendance on the following days last week. Please review and fix* :-
● Amravati : Monday, Tuesday, Wednesday, Thursday, Saturday
● Udaipur : Monday, Tuesday
● Jashpur : Monday, Tuesday, Wednesday, Thursday, Friday, Saturday
● Raipur : Monday, Tuesday, Wednesday, Thursday, Friday, Saturday
● Sarjapura : Monday
● Dantewada : Monday, Tuesday, Wednesday, Thursday, Friday, Saturday
● Delhi : Monday, Thursday

However , this does not take into account if any of these days (where there was missing attendance) was a campus holiday or not. So, we need to update the logic to check if its a holiday, and if it is, not list it as a day of missing attendance.

**Comment by Goldy2488** [comment]
Done
