### ISSUE TITLE
Moodle Issues

### ISSUE THREAD

**Issue by Goldy2488** [navgurukul/ghar#454]
- [ ] Get the empty object from Node when triggering the Curriculum Api. @ujjwal15718 
- [x] Some student not getting Moodle Data @Goldy2488

**Comment by Goldy2488** [comment]
11-11-24

Today I will investigate why 77 students are Empty in Ghar.

**Comment by ujjwal15718** [comment]
some user data is getting empty when triggering the Moodle function itself, the data is not in the database, and their status can be "not current" It should be "active" it will be when they participate or access some courses

**Comment by Goldy2488** [comment]
I investigated "why student data is empty in the ghar for Moodle," where I found some areas and resolved them, but today, my function does not work. I will try to debug my function.

**Comment by Goldy2488** [comment]
13-11-24
I investigated the Moodle bugs and resolved them. Today, we found a new issue: current modules were inserted incorrectly. I will work on it.

**Comment by Goldy2488** [comment]
14-11-24
I worked with Vijay and debugged why the correct modules were not inserted. It was done today, and the data was inserted successfully.

**Comment by Vijay-train** [comment]
All active Moodle issues are resolved 🥇
