### ISSUE TITLE
Slack Message : Some tags in slack messages are not resolving

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#52]
ghar sends several notifications on a weekly basis to #ghar_notifications_production channel.

These messages tag Indvidual with @ mentions. However some of the @ mentions are not resolving,

- in "Here’s weekly snapshot of whats happening in Ghar :house:" this message : `@anup` is not resolving
- in "Here’s the # of Students with attendance lesser than 87%" this message: `@shivanisuji` is not resolving

We need to investigate and fix this issue

**Comment by Goldy2488** [comment]
for now, all tags are working But in my research

- Usernames in Slack are automatically assigned based on the user's email address, often comprising a combination of their first and last name, email, or a random string.

**Comment by Goldy2488** [comment]
for more information: https://navgurukul.slack.com/archives/C053TRDJT5F/p1702706772869119
