### ISSUE TITLE
Slack Message : Change frequency of missing attendance slack message

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#53]
A weekly message is sent to #ghar_notifications_production" channel with the title ":scream_cat: You missed taking attendance on the following days last week. Please review and fix* :-"

Current behaviour
- This sends a message every Monday at 8 AM. It will list the campuses where attendance was not taken in the previous week ( ignoring sundays)

New behaviour needed
- This message should go out every working day ( Mon,Tue,Wed.Thu,Fri,Sat)
- It should then find if there was any missing attendance in last 6 working days (starting from pevious day)
- and then send the message

**Comment by Goldy2488** [comment]
The issue was resolved by updating the schedule from weekly to daily and it also checks for missing attendance over the last 28 days.
