### ISSUE TITLE
Not allow to take attendance if there are pending leaves for the Selected Campus.

### ISSUE THREAD

**Issue by VarshaRajput12** [navgurukul/ghar#54]
Not allow to take attendance if there are pending leaves for the Selected Campus. Show an Alert to notify the User.

**Comment by Vijay-train** [comment]
@VarshaRajput12 - Please add more details. If someone else picks up, they should have enough context

**Comment by VarshaRajput12** [comment]
Resolved the issue by adding a workflow on the submission of "Add Attendance Record" form in which I have wrote some deluge code to check the pending leaves for the selcted date.
Closing now.
