### ISSUE TITLE
Students - Per Campus/School report needs to show status breakup in the chart

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#57]
"Students - Per Campus/School" report needs to show breakdown of status's in the bars per campus.

https://www.loom.com/share/67d73db24bfe4c5d8b8332de662ce41b?sid=41841cec-898d-40c4-a2d0-72e2382033e1 see video for more details

**Comment by kajal8512** [comment]
Did the changes in the report of per Campus/School add status breakup in the tooltip.
