### ISSUE TITLE
Employee Management System

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#58]
There is a need to capture basic employee details such as employee phone, email, slack id, designation, whether an NG alumni or not, department, functional areas, skills, etc. Similar to how we have student management system, we need a employee management system. These employee records should be linked to their login profile. Benefits of such system is that it will simplify slack/email/sms notifications. For example, campus manager information just contains a name. To notify the campus managers we have to manually get their contact details and tag them. If we have a employee management system then the notification system can easily capture the required slack/email/phone id and notify the concerned employee. This would be required when we plan to implement granular user managment system.

In first iteration we just start with capturing phone, email, slack id, designation, NG alumni or not, and link to login user.

**Comment by Vijay-train** [comment]
This is not a priority. Closing
