### ISSUE TITLE
Slack Message - Need to send a daily Vacant seats per campus message

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#59]
Context - https://navgurukul.slack.com/archives/C01UC8AV8AJ/p1701955561199759

We want to send a daily slack message as below

It will be sent daily to the admissions-campusteams channel

![Image](https://github.com/navgurukul/ghar/assets/53718047/dc2dcd50-7ceb-445e-b9e2-a1995da1ebba)

-----------------------------------------------------------------------------------------------------------------------------------------------------

Campus capacity shall be divided into Student Capacity and Non Student Capacity.  User shall update these fields.

Following field shall be added to campus to capture different types of non students residing in campuses. User shall update these fields.
- Part-time Interns Count
- Externally Placed Alumni Count
- Campus Team Count: These are campus residential team members(Academic Associates, Cultural Associates, etc)
- Non-Campus Members Count: These are non campus residential team members(Ghar team members, placement team, mobilisation team)
- Non-Residential Members Count: These are non residential team members(Meraki team, Bootcamp team)

There shall be following fields to capture the actual occupancy
- Current Student occupancy - this field shall be auto updated whenever a student is assigned or unsigned to a campus. Also this occupancy shall be the sum of all student occupancy of each school in campus.
- Current Non Student occupancy - this field shall be the sum of Part time interns count, Externally placed alumni count, Campus NG team members residential count, Non campus NG team member count, NG team member non-residential count fields

A campus shall have set of schools. For each school following shall be captured
Unique Identifier -
- School Type(Sop, sod,etc)
- Max Student Capacity
- Student Size/Occupancy - this shall be auto updated when a student is assigned or unassigned from the school.
- School Manager
- School Team(list of user, optional)

Daily, following notification shall be sent:
Date
Students vs Non Students Occupancy -

Pune
- Student Capacity 160, Students Occupancy 170
- Non Student Capacity 20,  Non Students Occupancy 30(Part time interns 5, Externally placed alumni 5, NG team Campus 15,NG team Non Campus 3, NG Team non-residential 2)

Sarjapur
- Student Capacity 90, Student Occupancy 80
- Non Student Capacity 10, Non Students Occupancy 11(Part time interns 2, Externally placed alumni 2, NG team Campus 5,NG team Non Campus 1, NG Team non-residential 1)

Daily, following school wise vacancy notification shall be sent -
Date 
Active Students vs Max Capacity Report as available in Ghar
Amravati
- School of Programming: Vacant Seats = 5(Student Occupancy 10, Max Capacity 15)
- School of Design: Vacant Seats = 2(Student Occupancy 10, Max Capacity 12)

Dantewada
- School of Programming: Vacant Seats = 5(Student Occupancy 10, Max Capacity 15)
- School of Design: Vacant Seats = 2(Student Occupancy 10, Max Capacity 12)

Conversation Reference
![image](https://github.com/navgurukul/ghar/assets/117743777/72d11d04-0b8d-45eb-85a6-443fba97e78d)

**Comment by ujjwal15718** [comment]
The final message

Campus Vacancy Report for Jashpur (01-Feb-2024)
Total:Vacant Seats = 476 (Capacity = 565, Occupied = 89)
Students: Vacant = 436 (Capacity = 525, Occupied = 89)
     School of Management: Vacant = 100 (Capacity =  100, Occupied = 0 )
     School of Programming: Vacant = 120 (Capacity =  123, Occupied = 3 )
     School of Finance: Vacant = 117 (Capacity =  123, Occupied = 6 )
Non-Students: Vacant = 40 (Capacity = 40, Occupied = 0 )
    Part-Time Interns: 0
    Non-Residential NG Team Members: 0
    Externally Placed Alumni: 0
    Residential NG Team Members: 0
    Non-Campus NG Team Members: 0
This is the data as shown in ghar. Please reach out to the campus team below for any questions
Campus team:  
[@Sakshi Gangwar](https://navgurukul.slack.com/team/U045JSP9NTG)
[@Sudiksha (She/Her)](https://navgurukul.slack.com/team/U05QSN4NMJQ)
[@Anjali Vishwakarma (She/Her)](https://navgurukul.slack.com/team/U057NRCP7QS)

**Comment by Vijay-train** [comment]
This is implementeed
