### ISSUE TITLE
Ability to add holidays for more than one day

### ISSUE THREAD

**Issue by Vijay-train** [navgurukul/ghar#60]
In Ghar, we can only add Holidays per day. We need a functionality, where we can add multi day holidays. (Like - One may choose a start date end date of a holiday, and those many holidays should then be added).

Changes needed
- In the UI, to allow for multi day holidays
- Whereever the holidays are being used ( for eg - in FixAttendanceRatesForAllStudents , it checks for holidays by retreiving data from Holiday_List table), we should ensure that is not broken with multiple holidays
- There might be other places where Holiday_List is being used, should check and ensure that it works

**Comment by kajal8512** [comment]
1. I did changes in the UI, allow for multi day holidays, - I added a field in the form of holiday  "from and to date". 
2. I did the changes, Whereever the holidays are being used. 
     a. CampusAndStudents.FixAttendanceRatesForAllStudents
     b. Notifications.GetMissingDaysForCampusesLastWeek
In these two function holidays are using only. I modify the code of these two function. according to the new holidays field.

**Comment by Vijay-train** [comment]
@Vijay-train to review the above changes and revert

**Comment by kajal8512** [comment]
This feature is now in production.
