### ISSUE TITLE
While submitting the Transfer student we have to display an Alert about the Leaves deletion.

### ISSUE THREAD

**Issue by VarshaRajput12** [navgurukul/ghar#64]
While submitting the Transfer student we have to display an Alert to inform the user that the Future leaves will be deleted while transferring the student.

**Comment by Goldy2488** [comment]
With the help of the page, we can display the alert message.

**Comment by Vijay-train** [comment]
Check with @abhilashnavgurukul for the proper error message and then Please move the changes into the Ghar App

**Comment by Goldy2488** [comment]
I coordinated with @abhilashnavgurukul and he suggested some points for changing:
- add a note in the transfer student form for pre-informing.
- show all deleted leaves data that are coming in the alert box.

**Comment by abhilashnavgurukul** [comment]
A note informing student - "All future leaves of <Student Name> shall be deleted. You will have to reapply the leaves."

After transfer is performed, in the alert box - 
Following leaves have been delete
1. Leave Start Date , Leave End Date, Leave Type, Leave Status
2. Leave Start Date , Leave End Date, Leave Type, Leave Status

**Comment by Goldy2488** [comment]
Done, I did this by adding a Note on the Transfer form.
