### ISSUE TITLE
Ghar Summary slack message update for dropouts Students 

### ISSUE THREAD

**Issue by Goldy2488** [navgurukul/ghar#72]
In the ghar summary, the message has a requirement to update the number of dropout students by Nidhi Anarkat.

This is the message link:  https://navgurukul.slack.com/archives/C062V9H1ATZ/p1702869567710059

**Comment by Goldy2488** [comment]
I worked on the dropOut we are finding the dropOut student for the one week I added one field for getting the dropOut date and used it in the SendWeeklyGharSummary.

**Comment by Vijay-train** [comment]
As discussed, lets change to
""Flashback to last Friday, we had 816 active students, with 0 of them on unapproved leave. :umbrella_on_ground:. Also, 5 students dropped out""

**Comment by Goldy2488** [comment]
it was done in development.
