### ISSUE TITLE
Half Day Attendance Feature

### ISSUE THREAD

**Issue by shashi-NG** [navgurukul/ghar#77]
[](https://navgurukul.slack.com/archives/C068E4NTVD5/p1702617648547659)

The PMLs and AAs have raised a question. I wanted clarity if it is possible to inculcate in the Ghar app. If students study for half a day, can we mark their attendance for that half? Otherwise, what happens if they go outside and return to campus to study? It is not helping their attendance rate, resulting in them taking a whole day off even when not needed because even if they study, it has no impact on their attendance

Current Solution: reduce half-day leaves and encourage them to compensate for those hours on the same day and max within that week.

**Comment by Vijay-train** [comment]
This is not a requirement any more from campus teams. They are discouraging half day leaves
