### ISSUE TITLE
Change the slack message tags for Amravati.

### ISSUE THREAD

**Issue by VarshaRajput12** [navgurukul/ghar#81]
Change the slack message tags for Amravati. Instead of Priyanka kumari we have to tag Aanista malik and Atiya.
https://navgurukul.slack.com/archives/C05U0NQDVP1/p1704180782371449.

**Comment by VarshaRajput12** [comment]
Need to push it in Production.. then will close it

**Comment by Vijay-train** [comment]
ok, we will push it..

**Comment by Goldy2488** [comment]
Done
