### ISSUE TITLE
Prd update to account for max leave cap for students.

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#82]
We had capped College leaves to 39 leaves a year. However there was no cap for other leaves. Due to this it was not possible to flag students who takes more leaves. Campus team has formalized max leave cap for students. Update PRD based on this policy.
[NG_Student Attendance Policy_Nov2023.pdf](https://github.com/navgurukul/ghar/files/13856290/NG_Student.Attendance.Policy_Nov2023.pdf)

**Comment by Vijay-train** [comment]
There is no requirement for leave caps other than exam leaves. Closing this for now
