### ISSUE TITLE
Update to ensure leave calculation in Attendance rate is based on Nov 1 2023 date.

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#83]
It was decided to calculate attendance rate from Nov 1 onwards. However, leaves calculation was not based on Nov 1. Hence leaves taken before Nov 1 too were included in attendance rate calculation.

**Comment by Vijay-train** [comment]
No, the way its coded, attendance rate would ignore any attendance/leaves prior to Nov1 2023. Is there a specific repro for this case? Closing for now, please reopen if we have a specific repro
